import getGroupedMemberData from '../utils/getGroupedMemberData';

const expectedResult = {
  contributors: {
    facebook: [
      { majorContributor: true, login: 'acdlite', contributions: 1205 },
      { login: 'bgw', contributions: 24 },
    ],
    other: [
      { majorContributor: false, login: 'bvaughn', contributions: 366 },
      { majorContributor: false, login: 'chenglou', contributions: 222 },
      { majorContributor: true, login: 'gaearon', contributions: 1664 },
      { majorContributor: false, login: 'jimfb', contributions: 456 },
      { majorContributor: false, login: 'petehunt', contributions: 332 },
      { majorContributor: true, login: 'sebmarkbage', contributions: 1043 },
      { majorContributor: true, login: 'sophiebits', contributions: 1268 },
      { majorContributor: false, login: 'trueadm', contributions: 436 },
      { majorContributor: false, login: 'vjeux', contributions: 207 },
      { majorContributor: true, login: 'zpao', contributions: 1778 },
    ],
  },
  totals: { facebook: 1229, other: 10066 },
};

const mockContributors = [
  { majorContributor: true, login: 'zpao', contributions: 1778 },
  { majorContributor: true, login: 'gaearon', contributions: 1664 },
  { majorContributor: true, login: 'sophiebits', contributions: 1268 },
  { majorContributor: true, login: 'sebmarkbage', contributions: 1043 },
  { majorContributor: false, login: 'jimfb', contributions: 456 },
  { majorContributor: false, login: 'trueadm', contributions: 436 },
  { majorContributor: false, login: 'bvaughn', contributions: 366 },
  { majorContributor: false, login: 'petehunt', contributions: 332 },
  { majorContributor: false, login: 'chenglou', contributions: 222 },
  { majorContributor: true, login: 'acdlite', contributions: 1205 },
  { majorContributor: false, login: 'vjeux', contributions: 207 },
  { majorContributor: false, login: 'benjamn', contributions: 140 },
  { majorContributor: false, login: 'yungsters', contributions: 129 },
  { majorContributor: false, login: 'lunaruan', contributions: 124 },
  { majorContributor: false, login: 'subtleGradient', contributions: 115 },
  { majorContributor: false, login: 'nhunzaker', contributions: 94 },
  { majorContributor: false, login: 'necolas', contributions: 92 },
  { majorContributor: false, login: 'rickhanlonii', contributions: 91 },
  { majorContributor: false, login: 'syranide', contributions: 77 },
  { majorContributor: false, login: 'cpojer', contributions: 70 },
  { majorContributor: false, login: 'flarnie', contributions: 67 },
  { majorContributor: false, login: 'koba04', contributions: 67 },
  { majorContributor: false, login: 'aweary', contributions: 66 },
  { majorContributor: false, login: 'kassens', contributions: 59 },
  { majorContributor: false, login: 'eps1lon', contributions: 58 },
  { majorContributor: false, login: 'gnoff', contributions: 49 },
  { majorContributor: false, login: 'marocchino', contributions: 45 },
  { majorContributor: false, login: 'kohei-takata', contributions: 39 },
  { majorContributor: false, login: 'TheSavior', contributions: 30 },
  { login: 'chicoxyzzy', contributions: 29 },
  { login: 'keyz', contributions: 28 },
  { login: 'mcsheffrey', contributions: 26 },
  { login: 'bgw', contributions: 24 },
  { login: 'salazarm', contributions: 24 },
  { login: 'mondaychen', contributions: 23 },
  { login: 'NE-SmallTown', contributions: 22 },
  { login: 'joshduck', contributions: 21 },
  { login: 'aickin', contributions: 19 },
  { login: 'SimenB', contributions: 19 },
  { login: 'jquense', contributions: 18 },
  { login: 'philipp-spiess', contributions: 18 },
  { login: 'Daniel15', contributions: 17 },
  { login: 'iamdustan', contributions: 17 },
  { login: 'threepointone', contributions: 17 },
  { login: 'sammy-SC', contributions: 16 },
  { login: 'Simek', contributions: 15 },
  { login: 'fisherwebdev', contributions: 15 },
  { login: 'fabiomcosta', contributions: 15 },
  { login: 'sompylasar', contributions: 15 },
  { login: 'jordwalke', contributions: 15 },
  { login: 'raphamorim', contributions: 15 },
  { login: 'arkist', contributions: 14 },
  { login: 'josephsavona', contributions: 14 },
  { login: 'waldreiter', contributions: 14 },
  { login: 'iamchenxin', contributions: 14 },
  { login: 'bl00mber', contributions: 14 },
  { login: 'tomocchino', contributions: 14 },
  { login: 'elas7', contributions: 13 },
  { login: 'mroch', contributions: 12 },
  { login: 'graue', contributions: 12 },
  { login: 'ivanzotov', contributions: 11 },
  { login: 'kmeht', contributions: 11 },
  { login: 'tyao1', contributions: 11 },
  { login: 'DarkScorpion', contributions: 10 },
  { login: 'bhamodi', contributions: 10 },
  { login: 'RReverser', contributions: 10 },
  { login: 'leebyron', contributions: 10 },
  { login: 'lucasecdb', contributions: 10 },
  { login: 'Andarist', contributions: 10 },
  { login: 'motiz88', contributions: 10 },
  { login: 'fxxkscript', contributions: 10 },
  { login: 'poteto', contributions: 10 },
  { login: 'yangshun', contributions: 10 },
  { login: 'AnSavvides', contributions: 9 },
  { login: 'andreypopp', contributions: 9 },
  { login: 'clemmy', contributions: 9 },
  { login: 'taneliang', contributions: 9 },
  { login: 'hristo-kanchev', contributions: 9 },
  { login: 'jaredly', contributions: 9 },
  { login: 'joecritch', contributions: 9 },
  { login: 'JoshuaGross', contributions: 9 },
  { login: 'raunofreiberg', contributions: 9 },
  { login: 'rickbeerendonk', contributions: 9 },
  { login: 'yiminghe', contributions: 9 },
  { login: 'jddxf', contributions: 9 },
  { login: 'zertosh', contributions: 8 },
  { login: 'sun1one', contributions: 8 },
  { login: 'Biki-das', contributions: 8 },
  { login: 'behnammodi', contributions: 8 },
  { login: 'camsong', contributions: 8 },
  { login: 'hzoo', contributions: 8 },
  { login: 'ianobermiller', contributions: 8 },
  { login: 'jgebhardt', contributions: 8 },
  { login: 'SanderSpies', contributions: 8 },
  { login: 'wincent', contributions: 8 },
  { login: 'puradox', contributions: 8 },
  { login: 'andrewdavey', contributions: 7 },
  { login: 'DenrizSusam', contributions: 7 },
  { login: 'KonstHardy', contributions: 7 },
  { login: 'rbalicki2', contributions: 7 },
];

const mockMembers = [
  'aaronabramov',
  'acdlite',
  'adamgross42',
  'ahmadi18',
  'ahmed-shehata',
  'aigoncharov',
  'ajoulin',
  'alexholdenmiller',
  'alfozan',
  'amyreese',
  'anankervis',
  'anshulverma',
  'antiarchit',
  'apiri',
  'asm89',
  'assafgelber',
  'bgolub',
  'bgw',
  'bigfootjon',
  'binliu19',
  'bradzacher',
  'cdown',
  'cuva',
  'danharper',
];

test('getGroupedMemberData works', async () => {
  //console.log(JSON.stringify(await getGroupedMemberData(mockContributors, mockMembers)))
  expect(
    await getGroupedMemberData(mockContributors, mockMembers)
  ).toStrictEqual(expectedResult);
});
